name: destroy-ephemeral-rsc
on:
  workflow_dispatch: # Trigger this workflow manually
    inputs:
      environment:
        description: This will be used as TF's workspace
        required: true
        type: choice
        options:
            - dev
            - staging
            - prod
        default: 'dev'
      action:
        description: Choose between plan or destroy the environment
        required: true
        type: choice
        options:
          - plan
          - destroy
        default: destroy

  schedule: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "00 12 * * 1,2,3,4,5"        # Run 12PM CT, any day of the month, every month, from Mon to Fri

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
permissions:
  id-token: write # This is required for requesting the JWT from GitHub's OIDC provider
  contents: read  # This is required for actions/checkout

jobs:
  create-ephemeral-resources:
    uses: benhur-araujo/gh-reusable-workflows/.github/workflows/aws-iac.yaml@main
    with:
      plan: ${{ inputs.action == 'plan' }}
      destroy: ${{ inputs.action == 'destroy' || github.event_name == 'schedule' }}
      environment: dev
